-- MySQL Script generated by MySQL Workbench
-- Thu Dec 15 23:16:28 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema recipe
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema recipe
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `recipe` DEFAULT CHARACTER SET utf8mb3 ;
USE `recipe` ;

-- -----------------------------------------------------
-- Table `recipe`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recipe`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recipe`.`favorite_recipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recipe`.`favorite_recipe` (
  `recipe_name` VARCHAR(45) NOT NULL,
  `user_username` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`user_username`),
  INDEX `fk_favorite_recipe_user_idx` (`user_username` ASC) VISIBLE,
  CONSTRAINT `fk_favorite_recipe_user`
    FOREIGN KEY (`user_username`)
    REFERENCES `recipe`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recipe`.`recipe_review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recipe`.`recipe_review` (
  `recipe_name` VARCHAR(45) NOT NULL,
  `content` VARCHAR(45) NULL,
  `user_username` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`user_username`),
  INDEX `fk_recipe_review_user1_idx` (`user_username` ASC) VISIBLE,
  CONSTRAINT `fk_recipe_review_user1`
    FOREIGN KEY (`user_username`)
    REFERENCES `recipe`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
